package shoppingproject.gui;

import shoppingproject.dao.IDAO;

/**
 * INFO221 JFrame Form for application entry point in Main
 * @author jamal572
 */
public class ProductAdmin extends javax.swing.JFrame {
    
    private final IDAO productsList;
    /**
     * Constructor calls initComponents method generated by NetBeans
     * form creator
     * @param dao injected reference to the DAO from main
     */
    public ProductAdmin(IDAO dao) {
        initComponents();
        this.productsList = dao;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAdmin = new javax.swing.JLabel();
        btnProductAdmin = new javax.swing.JButton();
        btnViewProduct = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelAdmin.setText("Product Administration");

        btnProductAdmin.setText("Add New Product");
        btnProductAdmin.setToolTipText("Edit product");
        btnProductAdmin.setPreferredSize(new java.awt.Dimension(155, 23));
        btnProductAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductAdminActionPerformed(evt);
            }
        });

        btnViewProduct.setText("View Product");
        btnViewProduct.setMaximumSize(new java.awt.Dimension(67, 23));
        btnViewProduct.setMinimumSize(new java.awt.Dimension(67, 23));
        btnViewProduct.setPreferredSize(new java.awt.Dimension(67, 23));
        btnViewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProductActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.setMaximumSize(new java.awt.Dimension(95, 23));
        btnExit.setMinimumSize(new java.awt.Dimension(95, 23));
        btnExit.setPreferredSize(new java.awt.Dimension(23, 23));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(labelAdmin)
                    .addComponent(btnProductAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnViewProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAdmin)
                .addGap(28, 28, 28)
                .addComponent(btnProductAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Method that creates a JDialog form for adding new products
     * @param evt object generated by button clicked event for Add New Product
     * button
     */
    private void btnProductAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductAdminActionPerformed
        //Create instance of ProductEditor JDialog form   
        ProductEditor editProductDialog = new ProductEditor(this, true, productsList);
        
        //set location relative to admin menu
        editProductDialog.setLocationRelativeTo(this);
        
        //make it visible
        editProductDialog.setVisible(true);
        
    }//GEN-LAST:event_btnProductAdminActionPerformed
    
    /**
     * Method used to create a JDialog for reporting a list of saved products
     * @param evt object generated by button click event for ViewProduct button 
     */
    private void btnViewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProductActionPerformed
        //Create instance of ProductReport JDialog form
        ProductReport productReportDialog = new ProductReport(this, true, productsList);
        
        //set location relative to admin menu
        productReportDialog.setLocationRelativeTo(this);
        
        //make it visible
        productReportDialog.setVisible(true);
    }//GEN-LAST:event_btnViewProductActionPerformed

    /**
     * 
     * @param evt object generated by button click event for Exit button
     */
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

//    /**
//     * @param args the command line arguments - none
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ProductAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ProductAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ProductAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ProductAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ProductAdmin().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnProductAdmin;
    private javax.swing.JButton btnViewProduct;
    private javax.swing.JLabel labelAdmin;
    // End of variables declaration//GEN-END:variables
}
